### ISSUE TITLE
Peer to peer code review July 12th 2022

### ISSUE THREAD

**Issue by FabricioLatl** [iAmWaris97/iAmWaris97-Portfolio#3]
The code's looking great! Just one thing that I have noticed while reviewing the code.

  - Make sure to add a description on Alts that are Logos or are meaningful to the page, and not leave them blank. this helps accessibility.

https://github.com/iAmWaris97/iAmWaris97-Portfolio/blob/939ec55c18c29b7c4cf38ee09b8324e5bda8f1c9/index.html#L58-L74

**Comment by iAmWaris97** [comment]
Thank you for your kind review and comments.
Requested changes were made.
